
import __ASTRO_IMAGE_IMPORT_Z1UUKBI from "../../assets/indepartareTatuajLaser/IndepartareTatuajLaser1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Findepartare-cu-laser.md";
import __ASTRO_IMAGE_IMPORT_Z2nKxYX from "../../assets/indepartareTatuajLaser/IndepartareTatuajLaser2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Findepartare-cu-laser.md";
import __ASTRO_IMAGE_IMPORT_Zdeqhv from "../../assets/micropigmentarebuze/micropigmentareBuze1_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-buze.md";
import __ASTRO_IMAGE_IMPORT_Z1mjc6s from "../../assets/micropigmentarebuze/micropigmentareBuze2_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-buze.md";
import __ASTRO_IMAGE_IMPORT_Z1MjWCl from "../../assets/micropigmentarebuze/micropigmentareBuze3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-buze.md";
import __ASTRO_IMAGE_IMPORT_23ygJk from "../../assets/micropigmentareSprancene/micropigmentareSprancene1_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-sprancene.md";
import __ASTRO_IMAGE_IMPORT_165W49 from "../../assets/micropigmentareSprancene/micropigmentareSprancene1_2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-sprancene.md";
import __ASTRO_IMAGE_IMPORT_1qot9a from "../../assets/micropigmentareSprancene/micropigmentareSprancene2_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-sprancene.md";
export default new Map([["../../assets/indepartareTatuajLaser/IndepartareTatuajLaser1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Findepartare-cu-laser.md", __ASTRO_IMAGE_IMPORT_Z1UUKBI], ["../../assets/indepartareTatuajLaser/IndepartareTatuajLaser2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Findepartare-cu-laser.md", __ASTRO_IMAGE_IMPORT_Z2nKxYX], ["../../assets/micropigmentarebuze/micropigmentareBuze1_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-buze.md", __ASTRO_IMAGE_IMPORT_Zdeqhv], ["../../assets/micropigmentarebuze/micropigmentareBuze2_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-buze.md", __ASTRO_IMAGE_IMPORT_Z1mjc6s], ["../../assets/micropigmentarebuze/micropigmentareBuze3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-buze.md", __ASTRO_IMAGE_IMPORT_Z1MjWCl], ["../../assets/micropigmentareSprancene/micropigmentareSprancene1_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-sprancene.md", __ASTRO_IMAGE_IMPORT_23ygJk], ["../../assets/micropigmentareSprancene/micropigmentareSprancene1_2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-sprancene.md", __ASTRO_IMAGE_IMPORT_165W49], ["../../assets/micropigmentareSprancene/micropigmentareSprancene2_1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Farticles%2Fmicropigmentare-sprancene.md", __ASTRO_IMAGE_IMPORT_1qot9a]]);
		